# Generated by Django 5.1.1 on 2024-09-27 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='app_crud_doctor/images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'webp'])], verbose_name='Foto Del Doctor'),
        ),
    ]
